"""initial multi-tenant schema

Revision ID: 45440091f146
Revises: 
Create Date: 2026-10-01 22:07:50.797607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45440091f146'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='ck_companies_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(role = 'SUPER_ADMIN' AND company_id IS NULL) OR (role = 'COMPANY_ADMIN' AND company_id IS NOT NULL)", name='ck_admins_role_company'),
    sa.CheckConstraint("role IN ('SUPER_ADMIN', 'COMPANY_ADMIN')", name='ck_admins_role'),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='ck_admins_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id', 'company_id', name='uq_admins_id_company')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_company_id'), ['company_id'], unique=False)

    op.create_table('parking_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='ck_parking_lots_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_parking_lots_company_name'),
    sa.UniqueConstraint('id', 'company_id', name='uq_parking_lots_id_company')
    )
    with op.batch_alter_table('parking_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parking_lots_company_id'), ['company_id'], unique=False)

    op.create_table('admin_parking_lots',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('parking_lot_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id', 'company_id'], ['admins.id', 'admins.company_id'], name='fk_apl_admin_company', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parking_lot_id', 'company_id'], ['parking_lots.id', 'parking_lots.company_id'], name='fk_apl_lot_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('admin_id', 'parking_lot_id')
    )
    with op.batch_alter_table('admin_parking_lots', schema=None) as batch_op:
        batch_op.create_index('ix_apl_parking_lot', ['parking_lot_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.String(length=40), nullable=True),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parking_lot_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='ck_machines_status'),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['parking_lots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash'),
    sa.UniqueConstraint('serial_number')
    )
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machines_parking_lot_id'), ['parking_lot_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_admin_id'), ['admin_id'], unique=False)

    op.create_table('parking_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parking_lot_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('zone_name', sa.String(length=100), nullable=False),
    sa.Column('location_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['parking_lots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parking_lot_id', 'zone_name', name='uq_parking_zones_lot_name')
    )
    with op.batch_alter_table('parking_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parking_zones_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_zones_parking_lot_id'), ['parking_lot_id'], unique=False)

    op.create_table('violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('parking_lot_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('parking_zone_id', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('image_key', sa.String(length=500), nullable=True),
    sa.Column('image_status', sa.String(length=20), nullable=False),
    sa.Column('image_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("image_status IN ('PENDING', 'UPLOADED', 'FAILED', 'EXPIRED')", name='ck_violations_image_status'),
    sa.CheckConstraint("status IN ('DETECTED', 'NOTIFIED', 'IN_PROGRESS', 'RESOLVED')", name='ck_violations_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['parking_lots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parking_zone_id'], ['parking_zones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.create_index('ix_violations_company_status_detected', ['company_id', 'status', 'detected_at'], unique=False)
        batch_op.create_index('ix_violations_lot_detected', ['parking_lot_id', 'detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_violations_machine_id'), ['machine_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("channel IN ('IN_APP', 'EMAIL')", name='ck_notifications_channel'),
    sa.CheckConstraint("status IN ('PENDING', 'SENT', 'FAILED', 'READ')", name='ck_notifications_status'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('violation_id', 'admin_id', 'channel', name='uq_notifications_target')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_admin_status', ['admin_id', 'channel', 'status'], unique=False)

    op.create_table('violation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('previous_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('violation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_violation_history_violation_id'), ['violation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violation_history_violation_id'))

    op.drop_table('violation_history')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_admin_status')

    op.drop_table('notifications')
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violations_machine_id'))
        batch_op.drop_index('ix_violations_lot_detected')
        batch_op.drop_index('ix_violations_company_status_detected')

    op.drop_table('violations')
    with op.batch_alter_table('parking_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parking_zones_parking_lot_id'))
        batch_op.drop_index(batch_op.f('ix_parking_zones_machine_id'))

    op.drop_table('parking_zones')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_admin_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machines_parking_lot_id'))

    op.drop_table('machines')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_company_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('admin_parking_lots', schema=None) as batch_op:
        batch_op.drop_index('ix_apl_parking_lot')

    op.drop_table('admin_parking_lots')
    with op.batch_alter_table('parking_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parking_lots_company_id'))

    op.drop_table('parking_lots')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_company_id'))

    op.drop_table('admins')
    op.drop_table('companies')
    # ### end Alembic commands ###
