"""violation episodes

Revision ID: fcc09ab94851
Revises: 45440091f146
Create Date: 2026-10-01 23:57:26.505710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc09ab94851'
down_revision = '45440091f146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_detection_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('pending_violation_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('pending_since', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('clear_count', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('detection_count', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('end_reason', sa.String(length=30), nullable=True))

    # Existing rows were created one per photo, before episodes existed. Keep only the newest
    # violation of each machine as "vehicle still present" and mark the older ones as ended,
    # otherwise the unique index below could not be created.
    op.execute("UPDATE violations SET last_seen_at = detected_at WHERE last_seen_at IS NULL")
    op.execute(
        "UPDATE violations SET ended_at = detected_at, end_reason = 'SIGNAL_LOST' "
        "WHERE ended_at IS NULL AND id NOT IN (SELECT MAX(id) FROM violations GROUP BY machine_id)"
    )

    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.create_index('uq_violations_active_per_machine', ['machine_id'], unique=True, sqlite_where=sa.text('ended_at IS NULL'), postgresql_where=sa.text('ended_at IS NULL'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.drop_index('uq_violations_active_per_machine', sqlite_where=sa.text('ended_at IS NULL'), postgresql_where=sa.text('ended_at IS NULL'))
        batch_op.drop_column('end_reason')
        batch_op.drop_column('ended_at')
        batch_op.drop_column('detection_count')
        batch_op.drop_column('last_seen_at')

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_column('clear_count')
        batch_op.drop_column('pending_since')
        batch_op.drop_column('pending_violation_count')
        batch_op.drop_column('last_detection_at')

    # ### end Alembic commands ###
